general {
    output_format = "i3bar"
    colors = true
    interval = 1
}

order += "volume master"
order += "time"

time {
    format = "%Z: %H:%M:%S | %a %d %b %Y "
}

volume master {
    format = "VOL: %volume"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}
